const CATEGORY_MAP = {
  'Alexandrite':                    ['Alexandrite'],
  'Amethyst O':                     ['Amethyst'],
  'Aquamarine':                     ['Aquamarine'],
  'Aquamarine O':                   ['Aquamarine'],
  'Aquamarine+Emerald O':           ['Aquamarine', 'Emerald'],
  'Blue Topaz O':                   ['Topaz'],
  'chrome diopside O':              ['Chrome diopside'],
  'Diamond':                        ['Diamond'],
  'Diamond O':                      ['Diamond'],
  'Diamonds MEMO':                  ['Diamond'],
  'Diamonds Virtual':               ['Diamond'],
  'EM+AQ+PT O':                     ['Emerald', 'Aquamarine', 'Tourmaline'],
  'Emerald':                         ['Emerald'],
  'Emerald M':                      ['Emerald'],
  'Emerald Memo':                   ['Emerald'],
  'Emerald N':                      ['Emerald'],
  'Emerald O':                      ['Emerald'],
  'Emerald Virtual':                ['Emerald'],
  'Garnet O':                       ['Garnet'],
  'Green Tourmaline O':             ['Tourmaline'],
  'Kanari O':                       ['Kanari'],
  'Kunzite O':                      ['Kunzite'],
  'Morganite O':                    ['Morganite'],
  'N':                              ['Empty'],
  'O':                              ['Empty'],
  'Onyx O':                         ['Onyx'],
  'Opal O':                         ['Opal'],
  'Orange Topaz O':                 ['Topaz'],
  'Pink Tourmaline':                ['Tourmaline'],
  'Pink Tourmaline Memo':           ['Tourmaline'],
  'Pink Tourmaline O':              ['Tourmaline'],
  'Pink Tourmaline+Aquamarine O':   ['Tourmaline', 'Aquamarine'],
  'Pink Tourmaline+Kunzite O':      ['Tourmaline', 'Kunzite'],
  'Red Tourmaline O':               ['Tourmaline'],
  'Rubellite O':                    ['Rubellite'],
  'Ruby':                           ['Ruby'],
  'Ruby Memo':                      ['Ruby'],
  'Ruby O':                         ['Ruby'],
  'Sapphire':                       ['Sapphire'],
  'Sapphire Memo':                  ['Sapphire'],
  'Sapphire O':                     ['Sapphire'],
  'Sapphires Virtual':              ['Sapphire'],
  'Spinel':                         ['Spinel'],
  'Spinel Memo':                    ['Spinel'],
  'Spinel O':                       ['Spinel'],
  'Fancy':                           ['Diamond', 'Fancy'],
  'Tanzanite':                      ['Tanzanite'],
  'Tanzanite O':                    ['Tanzanite'],
  'Tourmaline Memo':                ['Tourmaline'],
  'Tourmaline O':                   ['Tourmaline'],
  'Tsavorite O':                    ['Tsavorite'],
};

export const getMappedCategories = (category) => {
  if (!category || category.trim() === '') return ['Empty'];
  return CATEGORY_MAP[category] || ['Empty'];
};

export default CATEGORY_MAP;
